# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: ["shutters"]

isn.devices.hhl_mirrors.HHL_Mirrors:
- name: hhl_mirrors
  prefix: 19idMR
  labels: ["mirror"]

isn.devices.softgluezynq.SoftGlueZynq:
- name: softglue
  prefix: acq_isn:SG

isn.devices.bda.BDA:
- name: bda_vert
  prefix: 19idBDA
  axis: V
  labels: ["bda"]

- name: bda_hor
  prefix: 19idBDA
  axis: H
  labels: ["bda"]

mic_common.devices.scan_record.ScanRecord:
- name: scan1
  prefix: 19idBLUE:scan1
- name: scan2
  prefix: 19idBLUE:scan2

mic_common.devices.save_data.SaveDataMic:
- name: savedata
  prefix: 19idBLUE:saveData_

ophyd.EpicsMotor:
- name: samx
  prefix: 19idBLUE:m1
  labels: ["motor"]
- name: samy
  prefix: 19idBLUE:m2
  labels: ["motor"]
- name: samz
  prefix: 19idBLUE:m3
  labels: ["motor"]
- name: samr
  prefix: 19idBLUE:m4
  labels: ["motor"]
- name: energy
  prefix: 19idBLUE:m5
  labels: ["motor"]
- name: temperature
  prefix: 19idBLUE:m6
  labels: ["motor"]

isn.devices.my_motor_bundle.MyMotorBundle:
- name: xz_motor
  prefix: 19idBLUE

mic_common.devices.xspress3.Xspress3:
- name: xrf_me7
  prefix: XSP3_7Chan:det1

mic_common.devices.eiger1m.Eiger1M:
- name: ptycho
  prefix: 19idPTYCHO:cam1

# isn.devices.tetramm.TetraMM:
# - name: tetramm1
#   prefix: 19idSFT:TetrAMM1

mic_common.devices.ad_fileplugin.DetHDF5:
- name: xrf_me7_hdf
  prefix: XSP3_7Chan:HDF1
- name: ptycho_hdf
  prefix: 19idPTYCHO:HDF1
- name: tetramm1_hdf

mic_common.devices.ad_fileplugin.DetNetCDF:
- name: tetramm1_netcdf

#     AD_XSP3_12Chan:
#       NAME: xrf_bse
#       PV_PREFIX: "XSP3_12Chan:det1:"
#       HDF5_PV_PREFIX: "XSP3_12Chan:HDF1:"


#     AD_EIGER_DIFFRACTION:
#       NAME: eigher_xrd
#       PV_PREFIX: "temp"


# TETRAMM1: "19idBPM:C:T4U"
# XSPRESS3_1: "XSP3_8Chan:det1"
# XSPRESS3_1_HDF5: "XSP3_8Chan:HDF1"
# SIMDET_CAM: "2idsimdet:cam1"
# SIMDET_HDF5: "2idsimdet:HDF1"
