# Written by StoredDict.
# Dictionary contents written: 2025-03-31 16:29:39.078944

beamline_id: demo_instrument
conda_prefix: /opt/homebrew/Caskroom/miniforge/base/envs/apsbits
databroker_catalog: temp
iconfig:
  APS_DEVICES_FILES: devices_aps_only.yml
  BEC:
    BASELINE: true
    HEADING: true
    PLOTS: true
    TABLE: true
  DATABROKER_CATALOG: temp
  DEVICES_FILES: devices.yml
  DM_SETUP_FILE: /home/dm/etc/dm.setup.sh
  ICONFIG_PATH: /Users/ecodrea/er_bs_test/src/eric_instrument/configs/iconfig.yml
  ICONFIG_VERSION: 2.0.0
  INSTRUMENT_FOLDER: configs
  INSTRUMENT_PATH: /Users/ecodrea/er_bs_test/src/eric_instrument/configs
  NEXUS_DATA_FILES:
    ENABLE: false
    FILE_EXTENSION: hdf
  OPHYD:
    CONTROL_LAYER: PyEpics
    TIMEOUTS:
      PV_CONNECTION: 5
      PV_READ: 5
      PV_WRITE: 5
  RUN_ENGINE:
    DEFAULT_METADATA:
      beamline_id: demo_instrument
      databroker_catalog: temp
      instrument_name: Most Glorious Scientific Instrument
      proposal_id: commissioning
    MD_PATH: .re_md_dict.yml
    MD_STORAGE_HANDLER: StoredDict
    USE_PROGRESS_BAR: false
  SPEC_DATA_FILES:
    ENABLE: true
    FILE_EXTENSION: dat
  USE_BLUESKY_MAGICS: true
  XMODE_DEBUG_LEVEL: Plain
instrument_name: Most Glorious Scientific Instrument
login_id: ecodrea@jinx
pid: 81046
proposal_id: commissioning
scan_id: 1
versions:
  apsbits: 1.0.0rc3
  apstools: 1.7.2
  bluesky: 1.13.1
  databroker: 1.2.5
  epics: 3.5.7
  h5py: 3.13.0
  intake: 0.6.4
  matplotlib: 3.10.1
  numpy: 1.26.4
  ophyd: 1.10.0
  pyRestTable: 2020.0.10
  pysumreg: 1.0.7
  python: 3.11.11
  spec2nexus: 2021.2.6
