# Guarneri-style device YAML configuration

mic_common.devices.scan_record.ScanRecord:
- name: scan1
  prefix: "2idd:scan1"
  labels: ["scanrecord"]
- name: scan2
  prefix: "2idd:scan2"
  labels: ["scanrecord"]
- name: fscan1
  prefix: "2idd:Fscan1"
  labels: ["scanrecord"]
- name: fscanh
  prefix: "2idd:FscanH"
  labels: ["scanrecord"]

mic_common.devices.save_data.SaveDataMic:
- name: savedata
  prefix: "2idd:saveData_"
  labels: ["savedata"]

s2idd_uprobe.devices.motor.Motor:
- name: samx
  prefix: 2idd:m40
  labels: ["motor"]
- name: samy
  prefix: 2idd:m39
  labels: ["motor"]
- name: samz
  prefix: 2idd:m36
  labels: ["motor"]

ophyd.EpicsSignal:
- name: fscanh_samx
  write_pv: 2idd:userCalc9.A
  read_pv: 2idd:userCalc9.A
  labels: ["usercalc"]
- name: fscanh_dwell
  write_pv: 2idd:Flyscans:Setup:DwellTime
  read_pv: 2idd:Flyscans:Setup:DwellTime
  labels: ["usercalc"]
- name: usercalc_tmm1_filename
  write_pv: 2iddfS1:userStringCalc1Enable
  read_pv: 2iddfS1:userStringCalc1Enable
  labels: ["usercalc"]
- name: usercalc_tmm1_filetemplate
  write_pv: 2iddfS1:userStringCalc2Enable
  read_pv: 2iddfS1:userStringCalc2Enable
  labels: ["usercalc"]
- name: usercalc_tmm2_filename
  write_pv: 2iddfS1:userStringCalc4Enable
  read_pv: 2iddfS1:userStringCalc4Enable
  labels: ["usercalc"]
- name: usercalc_tmm2_filetemplate
  write_pv: 2iddfS1:userStringCalc5Enable
  read_pv: 2iddfS1:userStringCalc5Enable
  labels: ["usercalc"]
- name: usercalc_xmap_filename
  write_pv: 2iddfS1:userStringCalc7Enable
  read_pv: 2iddfS1:userStringCalc7Enable
  labels: ["usercalc"]

mic_common.devices.sis3820.SIS3820:
- name: sis3820
  prefix: 2idd:3820
  labels: ["sis3820"]

s2idd_uprobe.devices.kohzu.KohzuMono:
- name: kohzu_mono
  prefix: "2ida2:"
  labels: ["mono"]

mic_common.devices.xmap.XMAP:
- name: xrf
  prefix: 2iddXMAP
  labels: ["xmap"]

mic_common.devices.ad_fileplugin.DetNetCDF:
- name: xrf_netcdf
  prefix: "2iddXMAP:netCDF1:"
  labels: ["netcdf"]
- name: tetramm1_netcdf
  prefix: "2iddtmm1:netCDF1:"
  labels: ["netcdf"]
- name: tetramm2_netcdf
  prefix: "2iddtmm2:netCDF1:"
  labels: ["netcdf"]
