# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog temp

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 2IDD
        instrument_name: XSD 2IDD-microprobe
        proposal_id: commissioning
        databroker_catalog: *databroker_catalog

    ### EPICS PV to use for the `scan_id`.
    ### Default: `RE.md["scan_id"]` (not using an EPICS PV)
    # SCAN_ID_PV: "IOC:bluesky_scan_id"

    ### Where to "autosave" the RE.md dictionary.
    ### Defaults:
    MD_PATH: .re_md_dict.yml

    ### The progress bar is nice to see,
    ### except when it clutters the output in Jupyter notebooks.
    ### Default: False
    USE_PROGRESS_BAR: false

### Best Effort Callback Configurations
### Defaults: all true
### except no plots in queueserver
BEC:
    BASELINE: true
    HEADING: true
    PLOTS: false
    TABLE: true

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
NEXUS_DATA_FILES:
    ENABLE: false
    FILE_EXTENSION: hdf

SPEC_DATA_FILES:
    ENABLE: false
    FILE_EXTENSION: dat

STORAGE:
  PATH: "/mnt/micdata1"

FILE_DELIMITER: "2idd"
SCAN_OVERHEAD: 0.3
XMAP:
    BUFFER: 124


# USERCALC:
#   FSCANH_POSITIONER: "2idd:userCalc9.A"
#   FSCANH_DWELL: "2idd:Flyscans:Setup:DwellTime"

# USERCALC_DISABLE:
#   TETRAMM1_FILENAME: "2iddfS1:userStringCalc1Enable"
#   TETRAMM1_FILETEMPLATE: "2iddfS1:userStringCalc2Enable"
#   TETRAMM2_FILENAME: "2iddfS1:userStringCalc4Enable"
#   TETRAMM2_FILETEMPLATE: "2iddfS1:userStringCalc5Enable"
#   XMAP_FILENAME: "2iddfS1:userStringCalc7Enable"

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: "/home/dm_id/etc/dm.setup.sh"

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    CONTROL_LAYER: PyEpics

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

XMODE_DEBUG_LEVEL: Plain
