# Configuration file example for the ptycho-xrf workflow

workflow : xrf
experimentName :  2025-2_Kim
fit : roi,nnls,matrix
filePath : 2idd_0430.mda
# dataDir : None
# nthreads : all
quantifyWith : None
detectors : 0
generateAvgH5 : False
addv9Layout : False
addExchange : False
exportCSV : False
updateTheta : None
updateAmps : None
updateQuantAmps : None
quickAndDirty : False
optimizeFitOverrideParams : None
optimizer : None
analysisMachine : polaris
demand : True
