# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog temp

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 19IDE
        instrument_name: XSD 19-IDE 
        proposal_id: commissioning
        databroker_catalog: *databroker_catalog

    USE_PROGRESS_BAR: true

### Best Effort Callback Configurations
### Defaults: all true (except no plots in queueserver)
# BEC:
#     BASELINE: false
#     HEADING: false
#     PLOTS: false
#     TABLE: false

STORAGE_PATH: "/net/s19data/export/ISN/bluesky_dev"

DEVICES:
  TETRAMM1: "19idBPM:C:T4U"
  SAVE_DATA: "19idBLUE:saveData_"
  SCAN1: "19idBLUE:scan1"
  SCAN2: "19idBLUE:scan2"
  # XSPRESS3_1: "XSP3_8Chan:det1"
  # XSPRESS3_1_HDF5: "XSP3_8Chan:HDF1"
  # SIMDET_CAM: "2idsimdet:cam1"
  # SIMDET_HDF5: "2idsimdet:HDF1"

POSITIONERS:
  X_MOTOR: "19idBLUE:m1"
  Y_MOTOR: "19idBLUE:m2"
  Z_MOTOR: "19idBLUE:m3"
  R_MOTOR: "19idBLUE:m4"
  XZ_MOTOR:
    M1: "19idBLUE:m1"
    M2: "19idBLUE:m3"
  ENERGY: "19idBLUE:m5"
  TEMPERATURE: "19idBLUE:m6"

AREA_DETECTOR:
    ### General configuration for area detectors.
    ALLOW_PLUGIN_WARMUP: true
    BLUESKY_FILES_ROOT: &BLUESKY_DATA_ROOT "/path/to/data/"
    IMAGE_DIR: "sub/directory/path"
    HDF5_FILE_TEMPLATE: "%s%s_%6.6d.h5"
  
    AD_XSP3_8Chan:
      NAME: xrf_me7
      PV_PREFIX: "XSP3_7Chan:det1:"
      HDF5_PV_PREFIX: "XSP3_7Chan:HDF1:"

    AD_XSP3_12Chan:
      NAME: xrf_bse
      PV_PREFIX: "XSP3_12Chan:det1:"
      HDF5_PV_PREFIX: "XSP3_12Chan:HDF1:"

    AD_EIGER_PTYCHO:
      NAME: eiger_ptycho
      PV_PREFIX: "temp"

    AD_EIGER_DIFFRACTION:
      NAME: eigher_xrd
      PV_PREFIX: "temp"

    ### Add configuration for specific detector(s).
    ### Suggestion:
    # ADSIM_16M:
    #     # IOC host: workstation_name
    #     IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    #     NAME: simdet16M
    #     PV_PREFIX: "simdet16m:"

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
# NEXUS_DATA_FILES:
#     FILE_EXTENSION: hdf
#     WARN_MISSING_CONTENT: true
# SPEC_DATA_FILES:
#     FILE_EXTENSION: dat

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: "/home/dm_id/etc/dm.setup.sh"

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    # CONTROL_LAYER: caproto

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

# Control detail of exception traces in IPython (console and notebook).
XMODE_DEBUG_LEVEL: Plain
