# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog temp

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 2IDD
        instrument_name: XSD 2IDD-microprobe
        proposal_id: commissioning
        databroker_catalog: *databroker_catalog

    USE_PROGRESS_BAR: true

### Best Effort Callback Configurations
### Defaults: all true (except no plots in queueserver)
# BEC:
#     BASELINE: false
#     HEADING: false
#     PLOTS: false
#     TABLE: false

STORAGE:
  PATH: "/mnt/micdata1"

DEVICES:
  SAVE_DATA: "2idd:saveData_"
  SCAN1: "2idd:scan1"
  SCAN2: "2idd:scan2"
  FSCAN1: "2idd:Fscan1"
  FSCANH: "2idd:FscanH"

POSITIONERS:
  X_MOTOR: "2idd:m40"
  Y_MOTOR: "2idd:m39"
  Z_MOTOR: "2idd:m36"
  SCAN_OVERHEAD: 0.3

KOHZU_MONO:
  NAME: kohzu_mono
  PV_PREFIX: "2ida2:"
  # NETCDF_PV_PREFIX: "2ida2:netCDF1:"
  # ENERGY: "2ida2:BraggEAO"



DETECTOR:
    ### General configuration for area detectors.
    ALLOW_PLUGIN_WARMUP: true
    BLUESKY_FILES_ROOT: &BLUESKY_DATA_ROOT "/path/to/data/"
    IMAGE_DIR: "sub/directory/path"
    HDF5_FILE_TEMPLATE: "%s%s_%6.6d.h5"
    FILE_DELIMITER: "2idd"

    XMAP_1Chan:
      NAME: xrf
      PV_PREFIX: "2iddXMAP:"
      NETCDF_PV_PREFIX: "2iddXMAP:netCDF1:"
      BUFFER: 124

    SIS3820:
      NAME: sis3820
      PV_PREFIX: "2idd:3820:"

    TETRAMM1:
      NAME: tetramm1
      PV_PREFIX: "2iddtmm1:"
      #HDF5_PV_PREFIX: "2iddtmm1:HDF1:"
      NETCDF_PV_PREFIX: "2iddtmm1:netCDF1:"

    TETRAMM2:
      NAME: tetramm2
      PV_PREFIX: "2iddtmm2:"
      NETCDF_PV_PREFIX: "2iddtmm2:netCDF1:"

USERCALC:
  FSCANH_POSITIONER: "2idd:userCalc9.A"
  FSCANH_DWELL: "2idd:Flyscans:Setup:DwellTime"

USERCALC_DISABLE:
  TETRAMM1_FILENAME: "2iddfS1:userStringCalc1Enable"
  TETRAMM1_FILETEMPLATE: "2iddfS1:userStringCalc2Enable"
  TETRAMM2_FILENAME: "2iddfS1:userStringCalc4Enable"
  TETRAMM2_FILETEMPLATE: "2iddfS1:userStringCalc5Enable"
  XMAP_FILENAME: "2iddfS1:userStringCalc7Enable"

    ### Add configuration for specific detector(s).
    ### Suggestion:
    # ADSIM_16M:
    #     # IOC host: workstation_name
    #     IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    #     NAME: simdet16M
    #     PV_PREFIX: "simdet16m:"

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
# NEXUS_DATA_FILES:
#     FILE_EXTENSION: hdf
#     WARN_MISSING_CONTENT: true
# SPEC_DATA_FILES:
#     FILE_EXTENSION: dat

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: "/home/dm_id/etc/dm.setup.sh"

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    # CONTROL_LAYER: caproto

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

# Control detail of exception traces in IPython (console and notebook).
XMODE_DEBUG_LEVEL: Plain
