# Configuration for the Bluesky instrument package.

# identify the version of this iconfig.yml file
ICONFIG_VERSION: 2.0.0

# Add additional configuration for use with your instrument.

### The short name for the databroker catalog.
DATABROKER_CATALOG: &databroker_catalog temp

### RunEngine configuration
RUN_ENGINE:
    DEFAULT_METADATA:
        beamline_id: 2IDD
        instrument_name: XSD 2-ID ISN
        proposal_id: commissioning
        databroker_catalog: *databroker_catalog

    ### EPICS PV to use for the `scan_id`.
    ### Default: `RE.md["scan_id"]` (not using an EPICS PV)
    # SCAN_ID_PV: f"{IOC}bluesky_scan_id"

    ### Directory to "autosave" the RE.md dictionary (uses PersistentDict).
    ### Default: HOME/.config/Bluesky_RunEngine_md'
    # MD_PATH: /home/beams/USERNAME/.config/Bluesky_RunEngine_md

    ### The progress bar is nice to see,
    ### except when it clutters the output in Jupyter notebooks.
    ### Default: True
    USE_PROGRESS_BAR: false

### Best Effort Callback Configurations
### Defaults: all true (except no plots in queueserver)
# BEC:
#     BASELINE: false
#     HEADING: false
#     PLOTS: false
#     TABLE: false

STORAGE_PATH: "/mnt/micdata1/2idd/"

DEVICES:
  TETRAMM1: "2idsft:TetrAMM1:"
  TETRAMM2: "2idsft:TetrAMM2:"
  TETRAMM3: "2idsft:TetrAMM3:"
  PROFILE_MOVE: "2idsft:"
  SAVE_DATA: "2idsft:saveData_"
  SCAN1: "2idsft:scan1"
  SCAN2: "2idsft:scan2"
  SOFT_GLUE: "2idMZ1:"
  POSITION_STREAM: "posvr:"
  XSPRESS3: "XSP3_1Chan:"

POSITIONERS:
  X_MOTOR: "2idsft:m1"
  Y_MOTOR: "2idsft:m2"
  Z_MOTOR: "2idsft:m3"
  R_MOTOR: "2idsft:m4"
  XZ_MOTOR:
    M1: "2idsft:m1"
    M2: "2idsft:m3"
  ENERGY: "2idsft:m5"
  TEMPERATURE: "2idsft:m6"

AREA_DETECTOR:
    ### General configuration for area detectors.
    ALLOW_PLUGIN_WARMUP: true
    BLUESKY_FILES_ROOT: &BLUESKY_DATA_ROOT "/path/to/data/"
    IMAGE_DIR: "sub/directory/path"
    HDF5_FILE_TEMPLATE: "%s%s_%6.6d.h5"
    ### Add configuration for specific detector(s).
    ### Suggestion:
    # ADSIM_16M:
    #     # IOC host: workstation_name
    #     IOC_FILES_ROOT: *BLUESKY_DATA_ROOT
    #     NAME: simdet16M
    #     PV_PREFIX: "simdet16m:"

### Support for known output file formats.
### Uncomment to use.  If undefined, will not write that type of file.
### Each callback should apply its configuration from here.
# NEXUS_DATA_FILES:
#     FILE_EXTENSION: hdf
#     WARN_MISSING_CONTENT: true
SPEC_DATA_FILES:
    FILE_EXTENSION: dat

### APS Data Management
### Use bash shell, deactivate all conda environments, source this file:
DM_SETUP_FILE: "/home/dm/etc/dm.setup.sh"

# ----------------------------------

OPHYD:
    ### Control layer for ophyd to communicate with EPICS.
    ### Default: PyEpics
    ### Choices: "PyEpics" or "caproto"
    # CONTROL_LAYER: caproto

    ### default timeouts (seconds)
    TIMEOUTS:
        PV_READ: &TIMEOUT 5
        PV_WRITE: *TIMEOUT
        PV_CONNECTION: *TIMEOUT

# Control detail of exception traces in IPython (console and notebook).
XMODE_DEBUG_LEVEL: Plain
