# Configuration for the master file generator.

OPTICS:
  kb_downstream_vertical:
    NAME: kb_downstream_vertical
    VALUE_PV: "19idKB:m11.VAL"
    RBV_PV: "19idKB:m11.RBV"
    UNITS_PV: "19idKB:m11.EGU" 
  kb_downstream_horizontal:
    NAME: kb_downstream_horizontal
    VALUE_PV: "19idKB:m12.VAL"
    RBV_PV: "19idKB:m12.RBV"
    UNITS_PV: "19idKB:m12.EGU"
  kb_upstream_vertical:
    NAME: kb_upstream_vertical
    VALUE_PV: "19idKB:m13.VAL"
    RBV_PV: "19idKB:m13.RBV"
    UNITS_PV: "19idKB:m13.EGU"
  kb_upstream_horizontal:
    NAME: kb_upstream_horizontal
    VALUE_PV: "19idKB:m14.VAL"
    RBV_PV: "19idKB:m14.RBV"
    UNITS_PV: "19idKB:m14.EGU"
  kb_sample_to_source:
    NAME: kb_sample_to_source
    VALUE_PV: "19idKB:m15.VAL"
    RBV_PV: "19idKB:m15.RBV"
    UNITS_PV: "19idKB:m15.EGU"
  
  
# SAMPLES:
#   TETRAMM1: "19idBPM:C:T4U"
#   SAVE_DATA: "19idBLUE:saveData_"
#   SCAN1: "19idBLUE:scan1"
#   SCAN2: "19idBLUE:scan2"

TETRAMM1_SETTING:
  TETRAMM1:
    NAME: tetramm1
    VALUE_PV: "19idSFT:TetrAMM1:Range"
  

XRD_ROBOT:
  TWO_THETA:
    NAME: two_theta
    VALUE_PV: "19IDRobot:TwoTheta"
    UNITS_PV: "19idXRD:m1.EGU"

PTYCHO_TABLE:
  AXIS_X:
    NAME: axis_x
    VALUE_PV: "19idPtycho:m1.VAL"
    RBV_PV: "19idPtycho:m1.RBV"
    UNITS_PV: "19idPtycho:m1.EGU"
  AXIS_Y: 
    NAME: axis_y
    VALUE_PV: "19idPtycho:m2.VAL"
    RBV_PV: "19idPtycho:m2.RBV"
    UNITS_PV: "19idPtycho:m2.EGU"
  AXIS_Z:
    NAME: axis_z
    VALUE_PV: "19idPtycho:m3.VAL"
    RBV_PV: "19idPtycho:m3.RBV"
    UNITS_PV: "19idPtycho:m3.EGU"
