# Configuration file example for the ptycho-xrf workflow

workflow : ptycho-xrf
experimentName :  s19iddm_ptycho_xrf_test
fit : roi,nnls
filePath : 003003.h5
dataDir : sample1/xspress3
# nthreads : all
quantifyWith : None
detectors : 3
generateAvgH5 : False
addv9Layout : False
addExchange : False
exportCSV : False
updateTheta : None
updateAmps : None
updateQuantAmps : None
quickAndDirty : False
optimizeFitOverrideParams : None
optimizer : None
analysisMachine : mona2
name : "003003"
sampleName : sample1
ptychoFilePath : scan_003003_eiger1m.hdf5
ptychoDetectorName : eiger
cropCenterXInPixels : None
cropCenterYInPixels : None
cropExtentXInPixels : None
cropExtentYInPixels : None
numGpus : None
probeEnergyInElectronVolts : None
detectorDistanceInMeters : None
preprocessingMachine : mona2
settings : /home/beams/USER19ID/ptychodusDefaults/nanomax3003.ini
demand : True