# Configuration file example for the ptycho-xrf workflow

workflow : ptychodus
experimentName :  s19iddm_ptychodus_test
filePath : scan_003003_eiger1m_master.hdf5
scanFilePath : 003003.h5
analysisMachine : mona2
name : "003003"
sampleName : sample1
ptychoDetectorName : eiger
cropCenterXInPixels : 546
cropCenterYInPixels : 736
cropExtentXInPixels : 128
cropExtentYInPixels : 128
numGpus : 0
probeEnergyInElectronVolts : 6722.0
detectorDistanceInMeters : 3.63
preprocessingMachine : mona2
settings : /home/beams/USER19ID/ptychodusDefaults/nanomax3003.ini
demand : True