# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- {creator: ophyd.sim.motor, name: sim_motor}
- {creator: ophyd.sim.noisy_det, name: sim_det}

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: ["shutters"]
  
mic_instrument.devices.hhl_mirrors.HHL_Mirrors:
- name: hhl_mirrors
  prefix: 19idMR
  labels: ["mirror"]

mic_instrument.devices.softgluezynq.SoftGlueZynq:
- name: softglue
  prefix: acq_isn:SG

mic_instrument.devices.bda.BDA:
- name: bda_vert
  prefix: 19idBDA
  axis: V
  labels: ["bda"]

- name: bda_hor
  prefix: 19idBDA
  axis: H
  labels: ["bda"]

mic_instrument.devices.ring.Ring:
- name: ring
  prefix: S-DCCT
  labels: ["ring"]

mic_instrument.devices.scan_record.ScanRecord:
- name: scan1
  prefix: 19idBLUE:scan1
- name: scan2
  prefix: 19idBLUE:scan2

mic_instrument.devices.save_data.SaveDataMic:
- name: savedata
  prefix: 19idBLUE:saveData_

ophyd.EpicsMotor:
- {name: x_motor, prefix: 19idBLUE:m1, labels: ["motor"]}
- {name: y_motor, prefix: 19idBLUE:m2, labels: ["motor"]}
- {name: z_motor, prefix: 19idBLUE:m3, labels: ["motor"]}
- {name: r_motor, prefix: 19idBLUE:m4, labels: ["motor"]}
- {name: energy, prefix: 19idBLUE:m5, labels: ["motor"]}
- {name: temperature, prefix: 19idBLUE:m6, labels: ["motor"]}

mic_instrument.devices.my_motor_bundle.MyMotorBundle:
- name: xz_motor
  prefix: 19idBLUE

mic_instrument.devices.tetramm_test.Tetramm:
- name: tetramm_1
  prefix: 19idSFT:TetrAMM1

mic_instrument.devices.xspress3.Xspress3:
- name: xrf_me7
  prefix: XSP3_7Chan:det1

mic_instrument.devices.eiger1m.Eiger1M:
- name: ptycho
  prefix: 19idPTYCHO:cam1

# mic_instrument.devices.tetramm.TetraMM:
# - name: tetramm1
#   prefix: 19idSFT:TetrAMM1

mic_instrument.devices.ad_fileplugin.DetHDF5:
- name: xrf_me7_hdf
  prefix: XSP3_7Chan:HDF1
- name: ptycho_hdf
  prefix: 19idPTYCHO:HDF1
- name: tetramm1_hdf

mic_instrument.devices.ad_fileplugin.DetNetCDF:
- name: tetramm1_netcdf

#     AD_XSP3_12Chan:
#       NAME: xrf_bse
#       PV_PREFIX: "XSP3_12Chan:det1:"
#       HDF5_PV_PREFIX: "XSP3_12Chan:HDF1:"


#     AD_EIGER_DIFFRACTION:
#       NAME: eigher_xrd
#       PV_PREFIX: "temp"


# TETRAMM1: "19idBPM:C:T4U"
# XSPRESS3_1: "XSP3_8Chan:det1"
# XSPRESS3_1_HDF5: "XSP3_8Chan:HDF1"
# SIMDET_CAM: "2idsimdet:cam1"
# SIMDET_HDF5: "2idsimdet:HDF1"
